- name: Create the lastest MariaDB repo
  copy: src=MariaDB-lastest.repo.j2 dest=/etc/yum.repos.d/MariaDB.repo

- name: Create GPG key for MariaDB repo
  copy: src=RPM-GPG-KEY-MariaDB dest=/etc/pki/rpm-gpg

- name: Add percona repo
  yum: name="http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm" state=present

- name: Add epel repo
  yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm" state=present
